# -*- coding: utf-8 -*-
"""Final_Project (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oH4laF4R9B-ZRmEgpRnuqIBqRzsTCCAm

# User Demographics EDA
**Name:** Marwa Mohamed Elhussieny

**ID:** 15

**Data source:** https://dummyjson.com/users?limit=100

## 0. Imports & Setup
"""

import requests
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

os.makedirs('plots', exist_ok=True)

sns.set_style('whitegrid')
sns.set_context('notebook', font_scale=1.2)
sns.set_palette('Set2')

"""## 1. Load Data"""

url = 'https://dummyjson.com/users?limit=100'
response = requests.get(url)
data = response.json()
df = pd.json_normalize(data['users'])
df.head()

"""## 2. Basic Data Exploration"""

print('Shape:', df.shape)

print('Columns:\n', df.columns.tolist())

print('Data types:\n')
df.dtypes

print('Missing values per column:')
df.isnull().sum()

print('Duplicate rows:', df.duplicated().sum())

df.describe()

for col in ['gender', 'bloodGroup', 'eyeColor', 'role', 'address.country']:
    if col in df.columns:
        print(f'--- {col} ---')
        print(df[col].value_counts(), '\n')

"""## 3. Data Cleaning"""

if 'address.country' not in df.columns:
    df['address.country'] = df['address'].apply(
        lambda x: x.get('country') if isinstance(x, dict) else None
    )

if 'address.city' not in df.columns:
    df['address.city'] = df['address'].apply(
        lambda x: x.get('city') if isinstance(x, dict) else None
    )

for col in ['age', 'height', 'weight']:
    if col in df.columns:
        df[col].fillna(df[col].median(), inplace=True)

print('Missing values after cleaning:')
df[['age', 'height', 'weight']].isnull().sum()

"""## 4. Analysis"""

avg_age = df['age'].mean()
print(f'Average age: {avg_age:.1f} years')

avg_age_gender = df.groupby('gender')['age'].mean()
print(avg_age_gender)

gender_counts = df['gender'].value_counts()
print(gender_counts)

top10_cities = df['address.city'].value_counts().head(10)
print(top10_cities)

avg_height = df['height'].mean()
avg_weight = df['weight'].mean()
print(f'Average height: {avg_height:.1f} cm')
print(f'Average weight: {avg_weight:.1f} kg')

corr_age_height = df['age'].corr(df['height'])
corr_age_weight = df['age'].corr(df['weight'])
print(f'Age vs Height: {corr_age_height:.3f}')
print(f'Age vs Weight: {corr_age_weight:.3f}')

"""## 5. Visualizations"""

plt.figure(figsize=(10, 6))
top10_cities.sort_values().plot(kind='barh', color=sns.color_palette('Set2', 10))
plt.title('Top 10 Cities by Number of Users')
plt.xlabel('Number of Users')
plt.ylabel('City')
plt.tight_layout()
plt.savefig('plots/plot1_top10_cities.png', dpi=150)
plt.show()

plt.figure(figsize=(9, 5))
sns.histplot(data=df, x='age', hue='gender', bins=12, multiple='stack')
plt.title('Age Distribution by Gender')
plt.xlabel('Age')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('plots/plot2_age_distribution.png', dpi=150)
plt.show()

plt.figure(figsize=(7, 5))
sns.boxplot(x='gender', y='age', data=df)
plt.title('Age Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Age')
plt.tight_layout()
plt.savefig('plots/plot3_age_boxplot.png', dpi=150)
plt.show()

plt.figure(figsize=(7, 5))
ax = sns.countplot(x='gender', data=df)
for p in ax.patches:
    ax.annotate(int(p.get_height()), (p.get_x() + p.get_width() / 2, p.get_height()),
                ha='center', va='bottom', fontsize=12)
plt.title('Number of Users per Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.tight_layout()
plt.savefig('plots/plot4_gender_count.png', dpi=150)
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(x='age', y='height', hue='gender', data=df, alpha=0.7)
plt.title(f'Age vs Height  (r = {corr_age_height:.3f})')
plt.xlabel('Age')
plt.ylabel('Height (cm)')
plt.tight_layout()
plt.savefig('plots/plot5_age_vs_height.png', dpi=150)
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(x='age', y='weight', hue='gender', data=df, alpha=0.7)
plt.title(f'Age vs Weight  (r = {corr_age_weight:.3f})')
plt.xlabel('Age')
plt.ylabel('Weight (kg)')
plt.tight_layout()
plt.savefig('plots/plot6_age_vs_weight.png', dpi=150)
plt.show()

plt.figure(figsize=(7, 5))
numeric_cols = df[['age', 'height', 'weight']].corr()
sns.heatmap(numeric_cols, annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap — Age, Height, Weight')
plt.tight_layout()
plt.savefig('plots/plot7_correlation_heatmap.png', dpi=150)
plt.show()